### ISSUE TITLE
Error in generating the output: accessExternalDTD' is not recognized

### ISSUE THREAD

**Issue by daneshka** [DaisyDiff/DaisyDiff#7]
[files-to-compare.zip](https://github.com/DaisyDiff/DaisyDiff/files/757887/files-to-compare.zip)
When I have **only this** image in my source and destination with a **different attribute** (like height) in the img tag  i have this error:

Is it because of the size of the image?

Comparing documents: C:/Users/smahajan/Desktop/JAR_FILES/old.html and C:/Users/smahajan/Desktop/JAR_FILES/new.html
Diff type: html
Writing html output to daisydiff.htm

.Warning:  org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
Compiler warnings:
  WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
Warning:  org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
Compiler warnings:
  WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
.Warning:  org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
Compiler warnings:
  WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
.java.lang.StackOverflowError
       at java.util.regex.Pattern.sequence(Pattern.java:2130)
       at java.util.regex.Pattern.expr(Pattern.java:1996)
       at java.util.regex.Pattern.compile(Pattern.java:1696)
       at java.util.regex.Pattern.<init>(Pattern.java:1351)
       at java.util.regex.Pattern.compile(Pattern.java:1028)
       at java.lang.String.replaceAll(String.java:2223)
       at org.outerj.daisy.diff.html.ancestor.ChangeText.clean(ChangeText.java:107)
       at org.outerj.daisy.diff.html.ancestor.ChangeText.addText(ChangeText.java:33)
       at org.outerj.daisy.diff.html.ancestor.ChangeText.addTextBrokenAcrossLines(ChangeText.java:90)
       at org.outerj.daisy.diff.html.ancestor.ChangeText.addTextCarefully(ChangeText.java:65)
       at org.outerj.daisy.diff.html.ancestor.ChangeText.addText(ChangeText.java:36)

**Comment by ataillefer** [comment]
Yes, it seems that `ChangeText#addTextCarefully`, because of its recursivity, is not meant to deal with huge unbreakable strings, as this Base64 encoded image...

The WARNING is unrelated.
